server:
  port: 8081

spring:
  cloud:
    discovery:
      client:
        simple:
          instances:
            backend-app:
              - uri: http://localhost:8082/app

    gateway:
      discovery:
        locator:
          enable: false
      routes:
        - id: swl
          uri: http://localhost:8081/
          predicates:
            - Path=/swl/**
        - id: backend-app
          uri: http://localhost:8082/
          predicates:
            - Path=/app/**


i2f:
  spring:
    web:
      mapping:
        enable: false
  swl:
    web:
      whiteListIn:
        - /swl/key
        - /swl/swapKey
      whiteListOut:
        - /swl/key
        - /swl/swapKey

logging:
  level:
    org.springframework.cloud.gateway: debug