i2f:
  springboot:
    dynamic:
      datasource:
        enable: true
        aop:
          enable: true
        initializer:
          enable: true
        multiply:
          master:
            driver: oracle.jdbc.OracleDriver
            url: jdbc:oracle:thin:@localhost:1521:orcl
            username: scott
            password: 123456
          slave:
            driver: com.mysql.cj.jdbc.Driver
            url: jdbc:mysql://localhost:3306/test_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
            username: root
            password: 123456

