server:
  port: 8082
  servlet:
    context-path: /app

logging:
  level:
    root: info
    i2f.secure.**.mapper: debug


spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    locale: zh_CN
    time-zone: Asia/Shanghai

i2f:
  swl:
    enable: true
  spring:
    cors:
      enable: true