# config 配置
i2f.springcloud.config-client.enable=true
# 是否开启定时拉去配置实现配置自动刷新，默认不开启
i2f.springcloud.config-client.refresh.pull.enable=false
# 默认30秒刷新一次
i2f.springcloud.config-client.refresh.pull.init-delay-seconds=30
i2f.springcloud.config-client.refresh.pull.interval-delay-seconds=30

