spring:
  profiles:
    active: dev

xproc4j:
  xml-locations: classpath*:procedure/**/*.xml;classpath*:com/**/procedure/*.xml
  watching-directories: classpath*:procedure/;classpath*:com/

ai:
  tools:
    file:
      root-path: ./ai-root
    selenium-web-search:
      enable: false
    playwright-web-search:
      enable: false
    command:
      enable: true