# secure 配置
i2f:
  springboot:
    config:
      secure:
        # 是否开启
        enable: true
        # asym秘钥的存储路径，默认../
        asym-store-path: ../
        # 响应字符集，默认UTF-8
        responseCharset: 'UTF-8'
        # Asym秘钥长度，默认1024，可选1024,2048
        asymKeySize: 1024
        # Symm秘钥长度，默认128，可选128,192,256
        symmKeySize: 128
        # 随机秘钥生成的随机数的最大值，默认8192
        randomKeyBound: 8192
        # 一次性消息的保持时间秒数，默认6*60
        # 这段时间内重复出现的nonce将会被认为是重放请求被拦截
        nonceTimeoutSeconds: 360
        # 是否启动动态Asym更新秘钥，默认true
        enableDynamicAsymKey: true
        # 每次更新秘钥的时长秒数，默认6*60
        dynamicRefreshDelaySeconds: 360
        # 最多保留多少历史秘钥，默认5
        dynamicMaxHistoriesCount: 5
        # 客户端秘钥对的获取策略，是否是本地生成交换策略，默认true
        enableSwapAsymKey: true
        # 用于存储安全头的请求头名称，默认sswh
        headerName: sswh
        # 安全头格式的分隔符，默认;
        headerSeparator: ;
        # 动态刷新Asym秘钥的响应头，默认skey
        dynamicKeyHeaderName: skey
        # URL加密的后端forward路径
        encUrlPath: /enc/
        # 请求URL参数加密的加密参数名
        parameterName: sswp
        # 默认的安全控制策略，也就是当注解和白名单都未配置时的策略模式，默认关闭
        defaultControl:
          # 入站是否安全
          in: true
          # 出站是否安全
          out: true
        # 白名单配置列表项，符合ant-match模式
        whiteList:
          # 进出站都忽略的列表清单
          bothPattens:
            - /file/**
            - /secure/key
          # 进站忽略的列表清单
          inPattens:
            - /common/upload/**
          # 出站忽略的列表清单
          outPattens:
            - /common/download/**
        # AOP功能
        aop:
          # 是否启用AOP功能，默认true
          # 改功能包含抛出核心filter的异常，使得能够通过ExceptionHandler进行捕获异常
          # 包含支持解密String类型的RequestParam请求参数
          # 包含controller为String类型返回值时的特殊处理
          # 因此不建议关闭此功能，关闭之后也需要自己进行覆盖实现
          enable: true
        # 内置的API接口
        api:
          # 是否开启默认的API响应Asym秘钥获取请求，默认true
          # 请求路径：/secure/key
          enable: true
        # 内置的URL请求路径转发接口
        enc-url-forward:
          # 是否开启enc的url解密请求转发，默认true
          # 请求路径: /enc/**
          enable: true
        # MVC替换converter为spring注册converter实现自定义
        # 当出现如果自定义的converter不生效时，需要开启
        # 当long类型需要转换为string类型给前端时，必须开启
        mvc:
          # 是否开启自定义替换converter
          enable: true
        # 针对jackson的拓展自定义配置
        jackson:
          # 是否开启自定义配置
          enable: true
          # 是否开启long类型转string类型给前端
          enableLongToString: true
          # 注意，LocalDateTime的格式化模式和spring.jackson.date-format配置一致
          # 因此，不用特殊配置
          # 定义LocalDate的格式化模式
          localDateFormat: yyyy-MM-dd
          # 定义LocalTime的格式化模式
          localTimeFormat: HH:mm:ss
