// Generated by JFlex 1.9.2 http://jflex.de/  (tweaked for IntelliJ platform)
// source: _OgnlLexer.flex

package i2f.turbo.idea.plugin.ognl.grammar.parser;

import com.intellij.lexer.FlexLexer;
import com.intellij.psi.tree.IElementType;

import static com.intellij.psi.TokenType.BAD_CHARACTER;
import static com.intellij.psi.TokenType.WHITE_SPACE;
import static i2f.turbo.idea.plugin.ognl.grammar.psi.OgnlTypes.*;


public class _OgnlLexer implements FlexLexer {

    /**
     * This character denotes the end of file
     */
    public static final int YYEOF = -1;

    /**
     * initial size of the lookahead buffer
     */
    private static final int ZZ_BUFFERSIZE = 16384;

    /**
     * lexical states
     */
    public static final int YYINITIAL = 0;

    /**
     * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
     * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
     * at the beginning of a line
     * l is of the form l = 2*k, k a non negative integer
     */
    private static final int ZZ_LEXSTATE[] = {
            0, 0
    };

    /**
     * Top-level table for translating characters to character classes
     */
    private static final int[] ZZ_CMAP_TOP = zzUnpackcmap_top();

    private static final String ZZ_CMAP_TOP_PACKED_0 =
            "\1\0\25\u0100\1\u0200\11\u0100\1\u0300\17\u0100\1\u0400\u10cf\u0100";

    private static int[] zzUnpackcmap_top() {
        int[] result = new int[4352];
        int offset = 0;
        offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
        return result;
    }

    private static int zzUnpackcmap_top(String packed, int offset, int[] result) {
        int i = 0;       /* index in packed string  */
        int j = offset;  /* index in unpacked array */
        int l = packed.length();
        while (i < l) {
            int count = packed.charAt(i++);
            int value = packed.charAt(i++);
            do result[j++] = value; while (--count > 0);
        }
        return j;
    }


    /**
     * Second-level tables for translating characters to character classes
     */
    private static final int[] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

    private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
            "\11\0\5\1\22\0\1\1\1\2\1\3\1\4\1\5" +
                    "\1\6\1\7\1\10\1\11\1\12\1\13\1\14\1\15" +
                    "\1\16\1\17\1\20\1\21\7\22\2\23\1\24\1\0" +
                    "\1\25\1\26\1\27\1\30\1\31\1\32\1\33\2\32" +
                    "\1\34\1\35\1\36\1\37\3\36\1\40\2\36\1\41" +
                    "\4\36\1\41\3\36\1\42\2\36\1\43\1\44\1\45" +
                    "\1\46\1\47\1\0\1\50\1\51\1\52\1\53\1\54" +
                    "\1\55\1\56\1\57\1\60\2\36\1\61\1\36\1\62" +
                    "\1\63\1\36\1\64\1\65\1\66\1\67\1\70\1\36" +
                    "\1\71\1\72\2\36\1\73\1\74\1\75\1\76\6\0" +
                    "\1\1\32\0\1\1\u01df\0\1\1\177\0\13\1\35\0" +
                    "\2\1\5\0\1\1\57\0\1\1\240\0\1\1\377\0";

    private static int[] zzUnpackcmap_blocks() {
        int[] result = new int[1280];
        int offset = 0;
        offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
        return result;
    }

    private static int zzUnpackcmap_blocks(String packed, int offset, int[] result) {
        int i = 0;       /* index in packed string  */
        int j = offset;  /* index in unpacked array */
        int l = packed.length();
        while (i < l) {
            int count = packed.charAt(i++);
            int value = packed.charAt(i++);
            do result[j++] = value; while (--count > 0);
        }
        return j;
    }

    /**
     * Translates DFA states to action switch labels.
     */
    private static final int[] ZZ_ACTION = zzUnpackAction();

    private static final String ZZ_ACTION_PACKED_0 =
            "\1\0\1\1\1\2\1\3\1\1\1\4\1\5\1\6" +
                    "\1\7\1\1\1\10\1\11\1\12\1\13\1\14\1\15" +
                    "\1\16\1\17\2\20\1\21\1\22\1\23\1\24\1\25" +
                    "\1\26\1\27\1\30\1\31\1\32\15\27\1\33\1\34" +
                    "\1\35\1\36\1\37\1\0\1\40\1\0\1\41\1\0" +
                    "\1\42\2\0\3\43\1\20\2\43\1\44\1\45\1\46" +
                    "\1\47\1\50\3\27\1\51\1\27\1\52\1\53\1\54" +
                    "\1\55\2\27\1\56\4\27\1\57\1\40\1\42\1\60" +
                    "\1\61\1\0\1\62\1\63\1\64\1\65\1\66\1\27" +
                    "\1\67\1\27\1\70\1\27\1\71\1\72\1\73\1\74" +
                    "\1\27\1\75\1\76\2\27\1\77\1\0\1\60\1\61" +
                    "\2\62\1\63\1\64\1\100\1\27\1\101\1\102\1\103" +
                    "\1\0\1\104\1\62\1\27\1\104\4\27\1\105";

    private static int[] zzUnpackAction() {
        int[] result = new int[131];
        int offset = 0;
        offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
        return result;
    }

    private static int zzUnpackAction(String packed, int offset, int[] result) {
        int i = 0;       /* index in packed string  */
        int j = offset;  /* index in unpacked array */
        int l = packed.length();
        while (i < l) {
            int count = packed.charAt(i++);
            int value = packed.charAt(i++);
            do result[j++] = value; while (--count > 0);
        }
        return j;
    }


    /**
     * Translates a state to a row index in the transition table
     */
    private static final int[] ZZ_ROWMAP = zzUnpackRowMap();

    private static final String ZZ_ROWMAP_PACKED_0 =
            "\0\0\0\77\0\176\0\275\0\374\0\77\0\77\0\77" +
                    "\0\u013b\0\u017a\0\77\0\77\0\77\0\77\0\77\0\77" +
                    "\0\77\0\77\0\u01b9\0\u01f8\0\77\0\u0237\0\u0276\0\u02b5" +
                    "\0\77\0\77\0\u02f4\0\77\0\77\0\77\0\u0333\0\u0372" +
                    "\0\u03b1\0\u03f0\0\u042f\0\u046e\0\u04ad\0\u04ec\0\u052b\0\u056a" +
                    "\0\u05a9\0\u05e8\0\u0627\0\77\0\u0666\0\77\0\77\0\77" +
                    "\0\374\0\77\0\u06a5\0\77\0\u017a\0\77\0\u06e4\0\u0723" +
                    "\0\u0762\0\u07a1\0\u07e0\0\u0762\0\u081f\0\u085e\0\77\0\77" +
                    "\0\77\0\77\0\u089d\0\u08dc\0\u091b\0\u095a\0\u02f4\0\u0999" +
                    "\0\u09d8\0\u0a17\0\u0a56\0\u0a95\0\u0ad4\0\u0b13\0\u02f4\0\u0b52" +
                    "\0\u0b91\0\u0bd0\0\u0c0f\0\77\0\374\0\u017a\0\u0c4e\0\u0c8d" +
                    "\0\u0ccc\0\u0d0b\0\u0d4a\0\u0d89\0\77\0\u02f4\0\u0dc8\0\u02f4" +
                    "\0\u0e07\0\u02f4\0\u0e46\0\u02f4\0\u02f4\0\u02f4\0\u02f4\0\u0e85" +
                    "\0\u02f4\0\u02f4\0\u0ec4\0\u0f03\0\u02f4\0\u0f42\0\77\0\u0762" +
                    "\0\u0f81\0\u0762\0\u0762\0\u0762\0\u02f4\0\u0fc0\0\u02f4\0\u02f4" +
                    "\0\u02f4\0\u0fff\0\u103e\0\77\0\u107d\0\77\0\u10bc\0\u10fb" +
                    "\0\u113a\0\u1179\0\u02f4";

    private static int[] zzUnpackRowMap() {
        int[] result = new int[131];
        int offset = 0;
        offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
        return result;
    }

    private static int zzUnpackRowMap(String packed, int offset, int[] result) {
        int i = 0;  /* index in packed string  */
        int j = offset;  /* index in unpacked array */
        int l = packed.length() - 1;
        while (i < l) {
            int high = packed.charAt(i++) << 16;
            result[j++] = high | packed.charAt(i++);
        }
        return j;
    }

    /**
     * The transition table of the DFA
     */
    private static final int[] ZZ_TRANS = zzUnpacktrans();

    private static final String ZZ_TRANS_PACKED_0 =
            "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\11" +
                    "\1\12\1\13\1\14\1\15\1\16\1\17\1\20\1\21" +
                    "\1\22\1\23\2\24\1\25\1\26\1\27\1\30\1\31" +
                    "\1\32\11\33\1\34\1\2\1\35\1\36\1\33\1\37" +
                    "\1\40\2\33\1\41\1\42\1\43\1\33\1\44\1\45" +
                    "\1\46\1\47\2\33\1\50\1\51\1\52\1\33\1\53" +
                    "\1\54\1\55\1\56\1\57\100\0\1\3\123\0\1\60" +
                    "\50\0\3\61\1\62\40\61\1\63\32\61\7\0\1\64" +
                    "\67\0\10\65\1\66\33\65\1\67\32\65\17\0\1\70" +
                    "\1\0\3\24\6\0\1\71\1\72\1\73\2\71\2\74" +
                    "\1\75\1\76\4\0\1\24\1\71\1\72\2\71\1\73" +
                    "\2\71\1\74\1\71\1\74\1\71\1\75\3\71\1\75" +
                    "\2\71\1\76\23\0\1\70\1\0\3\24\6\0\2\71" +
                    "\1\73\2\71\2\74\2\71\4\0\1\24\4\71\1\73" +
                    "\2\71\1\74\1\71\1\74\11\71\31\0\1\77\1\100" +
                    "\76\0\1\101\76\0\1\102\1\103\70\0\3\33\6\0" +
                    "\11\33\4\0\24\33\25\0\3\33\6\0\11\33\4\0" +
                    "\13\33\1\104\10\33\25\0\3\33\6\0\11\33\4\0" +
                    "\1\33\1\105\12\33\1\106\7\33\25\0\3\33\6\0" +
                    "\11\33\4\0\15\33\1\107\6\33\25\0\3\33\6\0" +
                    "\11\33\4\0\1\33\1\110\22\33\25\0\3\33\6\0" +
                    "\11\33\4\0\20\33\1\111\3\33\25\0\3\33\6\0" +
                    "\11\33\4\0\13\33\1\112\10\33\25\0\3\33\6\0" +
                    "\11\33\4\0\20\33\1\113\3\33\25\0\3\33\6\0" +
                    "\11\33\4\0\5\33\1\114\6\33\1\115\4\33\1\116" +
                    "\2\33\25\0\3\33\6\0\11\33\4\0\16\33\1\117" +
                    "\5\33\25\0\3\33\6\0\11\33\4\0\10\33\1\120" +
                    "\13\33\25\0\3\33\6\0\11\33\4\0\16\33\1\121" +
                    "\5\33\25\0\3\33\6\0\11\33\4\0\17\33\1\122" +
                    "\4\33\25\0\3\33\6\0\11\33\4\0\14\33\1\123" +
                    "\7\33\100\0\1\124\2\0\3\61\1\125\40\61\1\63" +
                    "\32\61\10\65\1\126\33\65\1\67\32\65\21\0\3\127" +
                    "\74\0\3\71\6\0\11\71\4\0\24\71\25\0\2\130" +
                    "\1\71\6\0\11\71\4\0\1\130\23\71\22\0\1\131" +
                    "\2\0\3\132\6\0\11\71\4\0\24\71\25\0\2\133" +
                    "\1\71\6\0\11\71\4\0\1\133\23\71\25\0\3\134" +
                    "\6\0\4\134\5\71\4\0\7\134\15\71\33\0\1\135" +
                    "\70\0\3\33\6\0\11\33\4\0\4\33\1\136\17\33" +
                    "\25\0\3\33\6\0\11\33\4\0\13\33\1\137\10\33" +
                    "\25\0\3\33\6\0\11\33\4\0\16\33\1\140\5\33" +
                    "\25\0\3\33\6\0\11\33\4\0\12\33\1\141\11\33" +
                    "\25\0\3\33\6\0\11\33\4\0\5\33\1\142\16\33" +
                    "\25\0\3\33\6\0\11\33\4\0\17\33\1\143\4\33" +
                    "\25\0\3\33\6\0\11\33\4\0\5\33\1\144\16\33" +
                    "\25\0\3\33\6\0\11\33\4\0\15\33\1\145\4\33" +
                    "\1\146\1\33\25\0\3\33\6\0\11\33\4\0\20\33" +
                    "\1\147\3\33\25\0\3\33\6\0\11\33\4\0\12\33" +
                    "\1\150\11\33\25\0\3\33\6\0\11\33\4\0\12\33" +
                    "\1\151\3\33\1\152\5\33\25\0\3\33\6\0\11\33" +
                    "\4\0\21\33\1\153\2\33\25\0\3\33\6\0\11\33" +
                    "\4\0\10\33\1\154\13\33\25\0\3\33\6\0\11\33" +
                    "\4\0\16\33\1\155\5\33\25\0\3\127\10\0\1\156" +
                    "\1\157\1\0\1\157\7\0\1\127\4\0\1\156\1\157" +
                    "\1\0\1\157\40\0\2\130\1\71\6\0\5\71\2\160" +
                    "\2\71\4\0\1\130\7\71\1\160\1\71\1\160\11\71" +
                    "\25\0\3\161\74\0\3\132\6\0\5\71\2\162\2\71" +
                    "\4\0\1\132\7\71\1\162\1\71\1\162\11\71\25\0" +
                    "\2\133\1\71\6\0\5\71\2\163\2\71\4\0\1\133" +
                    "\7\71\1\163\1\71\1\163\11\71\25\0\3\134\6\0" +
                    "\4\134\1\71\2\164\2\71\4\0\7\134\1\71\1\164" +
                    "\1\71\1\164\11\71\25\0\3\33\6\0\11\33\4\0" +
                    "\4\33\1\165\17\33\25\0\3\33\6\0\11\33\4\0" +
                    "\17\33\1\153\4\33\25\0\3\33\6\0\11\33\4\0" +
                    "\20\33\1\166\3\33\25\0\3\33\6\0\11\33\4\0" +
                    "\12\33\1\167\11\33\25\0\3\33\6\0\11\33\4\0" +
                    "\5\33\1\170\16\33\25\0\3\33\6\0\11\33\4\0" +
                    "\16\33\1\171\5\33\22\0\1\172\2\0\3\173\74\0" +
                    "\3\161\13\0\2\174\6\0\1\161\7\0\1\174\1\0" +
                    "\1\174\36\0\3\33\6\0\11\33\4\0\1\33\1\175" +
                    "\22\33\25\0\3\173\74\0\3\173\11\0\1\176\1\0" +
                    "\1\176\7\0\1\173\5\0\1\176\1\0\1\176\40\0" +
                    "\3\33\6\0\11\33\4\0\13\33\1\177\10\33\25\0" +
                    "\3\33\6\0\11\33\4\0\3\33\1\200\20\33\25\0" +
                    "\3\33\6\0\11\33\4\0\5\33\1\201\16\33\25\0" +
                    "\3\33\6\0\11\33\4\0\14\33\1\202\7\33\25\0" +
                    "\3\33\6\0\11\33\4\0\6\33\1\203\15\33\4\0";

    private static int[] zzUnpacktrans() {
        int[] result = new int[4536];
        int offset = 0;
        offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
        return result;
    }

    private static int zzUnpacktrans(String packed, int offset, int[] result) {
        int i = 0;       /* index in packed string  */
        int j = offset;  /* index in unpacked array */
        int l = packed.length();
        while (i < l) {
            int count = packed.charAt(i++);
            int value = packed.charAt(i++);
            value--;
            do result[j++] = value; while (--count > 0);
        }
        return j;
    }


    /* error codes */
    private static final int ZZ_UNKNOWN_ERROR = 0;
    private static final int ZZ_NO_MATCH = 1;
    private static final int ZZ_PUSHBACK_2BIG = 2;

    /* error messages for the codes above */
    private static final String[] ZZ_ERROR_MSG = {
            "Unknown internal scanner error",
            "Error: could not match input",
            "Error: pushback value was too large"
    };

    /**
     * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
     */
    private static final int[] ZZ_ATTRIBUTE = zzUnpackAttribute();

    private static final String ZZ_ATTRIBUTE_PACKED_0 =
            "\1\0\1\11\3\1\3\11\2\1\10\11\2\1\1\11" +
                    "\3\1\2\11\1\1\3\11\15\1\1\11\1\1\3\11" +
                    "\1\0\1\11\1\0\1\11\1\0\1\11\2\0\6\1" +
                    "\4\11\21\1\1\11\4\1\1\0\3\1\1\11\20\1" +
                    "\1\0\1\11\12\1\1\0\1\1\1\11\1\1\1\11" +
                    "\5\1";

    private static int[] zzUnpackAttribute() {
        int[] result = new int[131];
        int offset = 0;
        offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
        return result;
    }

    private static int zzUnpackAttribute(String packed, int offset, int[] result) {
        int i = 0;       /* index in packed string  */
        int j = offset;  /* index in unpacked array */
        int l = packed.length();
        while (i < l) {
            int count = packed.charAt(i++);
            int value = packed.charAt(i++);
            do result[j++] = value; while (--count > 0);
        }
        return j;
    }

    /**
     * the input device
     */
    private java.io.Reader zzReader;

    /**
     * the current state of the DFA
     */
    private int zzState;

    /**
     * the current lexical state
     */
    private int zzLexicalState = YYINITIAL;

    /**
     * this buffer contains the current text to be matched and is
     * the source of the yytext() string
     */
    private CharSequence zzBuffer = "";

    /**
     * the textposition at the last accepting state
     */
    private int zzMarkedPos;

    /**
     * the current text position in the buffer
     */
    private int zzCurrentPos;

    /**
     * startRead marks the beginning of the yytext() string in the buffer
     */
    private int zzStartRead;

    /**
     * endRead marks the last character in the buffer, that has been read
     * from input
     */
    private int zzEndRead;

    /**
     * zzAtEOF == true <=> the scanner is at the EOF
     */
    private boolean zzAtEOF;

    /**
     * Number of newlines encountered up to the start of the matched text.
     */
    @SuppressWarnings("unused")
    private int yyline;

    /**
     * Number of characters from the last newline up to the start of the matched text.
     */
    @SuppressWarnings("unused")
    protected int yycolumn;

    /**
     * Number of characters up to the start of the matched text.
     */
    @SuppressWarnings("unused")
    private long yychar;

    /**
     * Whether the scanner is currently at the beginning of a line.
     */
    @SuppressWarnings("unused")
    private boolean zzAtBOL = true;

    /**
     * Whether the user-EOF-code has already been executed.
     */
    @SuppressWarnings("unused")
    private boolean zzEOFDone;

    /* user code: */
    public _OgnlLexer() {
        this((java.io.Reader) null);
    }


    /**
     * Creates a new scanner
     *
     * @param in the java.io.Reader to read input from.
     */
    public _OgnlLexer(java.io.Reader in) {
        this.zzReader = in;
    }


    /**
     * Returns the maximum size of the scanner buffer, which limits the size of tokens.
     */
    private int zzMaxBufferLen() {
        return Integer.MAX_VALUE;
    }

    /**
     * Whether the scanner buffer can grow to accommodate a larger token.
     */
    private boolean zzCanGrow() {
        return true;
    }

    /**
     * Translates raw input code points to DFA table row
     */
    private static int zzCMap(int input) {
        int offset = input & 255;
        return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
    }

    public final int getTokenStart() {
        return zzStartRead;
    }

    public final int getTokenEnd() {
        return getTokenStart() + yylength();
    }

    public void reset(CharSequence buffer, int start, int end, int initialState) {
        zzBuffer = buffer;
        zzCurrentPos = zzMarkedPos = zzStartRead = start;
        zzAtEOF = false;
        zzAtBOL = true;
        zzEndRead = end;
        yybegin(initialState);
    }

    /**
     * Refills the input buffer.
     *
     * @return {@code false}, iff there was new input.
     * @throws java.io.IOException if any I/O-Error occurs
     */
    private boolean zzRefill() throws java.io.IOException {
        return true;
    }


    /**
     * Returns the current lexical state.
     */
    public final int yystate() {
        return zzLexicalState;
    }


    /**
     * Enters a new lexical state
     *
     * @param newState the new lexical state
     */
    public final void yybegin(int newState) {
        zzLexicalState = newState;
    }


    /**
     * Returns the text matched by the current regular expression.
     */
    public final CharSequence yytext() {
        return zzBuffer.subSequence(zzStartRead, zzMarkedPos);
    }


    /**
     * Returns the character at position {@code pos} from the
     * matched text.
     * <p>
     * It is equivalent to yytext().charAt(pos), but faster
     *
     * @param pos the position of the character to fetch.
     *            A value from 0 to yylength()-1.
     * @return the character at position pos
     */
    public final char yycharat(int pos) {
        return zzBuffer.charAt(zzStartRead + pos);
    }


    /**
     * Returns the length of the matched text region.
     */
    public final int yylength() {
        return zzMarkedPos - zzStartRead;
    }


    /**
     * Reports an error that occurred while scanning.
     * <p>
     * In a wellformed scanner (no or only correct usage of
     * yypushback(int) and a match-all fallback rule) this method
     * will only be called with things that "Can't Possibly Happen".
     * If this method is called, something is seriously wrong
     * (e.g. a JFlex bug producing a faulty scanner etc.).
     * <p>
     * Usual syntax/scanner level error handling should be done
     * in error fallback rules.
     *
     * @param errorCode the code of the errormessage to display
     */
    private void zzScanError(int errorCode) {
        String message;
        try {
            message = ZZ_ERROR_MSG[errorCode];
        } catch (ArrayIndexOutOfBoundsException e) {
            message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
        }

        throw new Error(message);
    }


    /**
     * Pushes the specified amount of characters back into the input stream.
     * <p>
     * They will be read again by then next call of the scanning method
     *
     * @param number the number of characters to be read again.
     *               This number must not be greater than yylength()!
     */
    public void yypushback(int number) {
        if (number > yylength())
            zzScanError(ZZ_PUSHBACK_2BIG);

        zzMarkedPos -= number;
    }


    /**
     * Resumes scanning until the next regular expression is matched,
     * the end of input is encountered or an I/O-Error occurs.
     *
     * @return the next token
     * @throws java.io.IOException if any I/O-Error occurs
     */
    public IElementType advance() throws java.io.IOException {
        int zzInput;
        int zzAction;

        // cached fields:
        int zzCurrentPosL;
        int zzMarkedPosL;
        int zzEndReadL = zzEndRead;
        CharSequence zzBufferL = zzBuffer;

        int[] zzTransL = ZZ_TRANS;
        int[] zzRowMapL = ZZ_ROWMAP;
        int[] zzAttrL = ZZ_ATTRIBUTE;

        while (true) {
            zzMarkedPosL = zzMarkedPos;

            zzAction = -1;

            zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

            zzState = ZZ_LEXSTATE[zzLexicalState];

            // set up zzAction for empty match case:
            int zzAttributes = zzAttrL[zzState];
            if ((zzAttributes & 1) == 1) {
                zzAction = zzState;
            }


            zzForAction:
            {
                while (true) {

                    if (zzCurrentPosL < zzEndReadL) {
                        zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL);
                        zzCurrentPosL += Character.charCount(zzInput);
                    } else if (zzAtEOF) {
                        zzInput = YYEOF;
                        break zzForAction;
                    } else {
                        // store back cached positions
                        zzCurrentPos = zzCurrentPosL;
                        zzMarkedPos = zzMarkedPosL;
                        boolean eof = zzRefill();
                        // get translated positions and possibly new buffer
                        zzCurrentPosL = zzCurrentPos;
                        zzMarkedPosL = zzMarkedPos;
                        zzBufferL = zzBuffer;
                        zzEndReadL = zzEndRead;
                        if (eof) {
                            zzInput = YYEOF;
                            break zzForAction;
                        } else {
                            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL);
                            zzCurrentPosL += Character.charCount(zzInput);
                        }
                    }
                    int zzNext = zzTransL[zzRowMapL[zzState] + zzCMap(zzInput)];
                    if (zzNext == -1) break zzForAction;
                    zzState = zzNext;

                    zzAttributes = zzAttrL[zzState];
                    if ((zzAttributes & 1) == 1) {
                        zzAction = zzState;
                        zzMarkedPosL = zzCurrentPosL;
                        if ((zzAttributes & 8) == 8) break zzForAction;
                    }

                }
            }

            // store back cached position
            zzMarkedPos = zzMarkedPosL;

            if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
                zzAtEOF = true;
                return null;
            } else {
                switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
                    case 1: {
                        return BAD_CHARACTER;
                    }
                    // fall through
                    case 70:
                        break;
                    case 2: {
                        return WHITE_SPACE;
                    }
                    // fall through
                    case 71:
                        break;
                    case 3: {
                        return OP_EXCLAM;
                    }
                    // fall through
                    case 72:
                        break;
                    case 4: {
                        return TERM_SHARP;
                    }
                    // fall through
                    case 73:
                        break;
                    case 5: {
                        return TERM_DOLLAR;
                    }
                    // fall through
                    case 74:
                        break;
                    case 6: {
                        return OP_MOD;
                    }
                    // fall through
                    case 75:
                        break;
                    case 7: {
                        return OP_BIT_AND;
                    }
                    // fall through
                    case 76:
                        break;
                    case 8: {
                        return TERM_PAREN_L;
                    }
                    // fall through
                    case 77:
                        break;
                    case 9: {
                        return TERM_PAREN_R;
                    }
                    // fall through
                    case 78:
                        break;
                    case 10: {
                        return OP_MUL;
                    }
                    // fall through
                    case 79:
                        break;
                    case 11: {
                        return OP_ADD;
                    }
                    // fall through
                    case 80:
                        break;
                    case 12: {
                        return TERM_COMMA;
                    }
                    // fall through
                    case 81:
                        break;
                    case 13: {
                        return OP_SUB;
                    }
                    // fall through
                    case 82:
                        break;
                    case 14: {
                        return TERM_DOT;
                    }
                    // fall through
                    case 83:
                        break;
                    case 15: {
                        return OP_DIV;
                    }
                    // fall through
                    case 84:
                        break;
                    case 16: {
                        return TERM_CONST_NUMBER;
                    }
                    // fall through
                    case 85:
                        break;
                    case 17: {
                        return TERM_COLON;
                    }
                    // fall through
                    case 86:
                        break;
                    case 18: {
                        return OP_LT;
                    }
                    // fall through
                    case 87:
                        break;
                    case 19: {
                        return OP_ASSIGN;
                    }
                    // fall through
                    case 88:
                        break;
                    case 20: {
                        return OP_GT;
                    }
                    // fall through
                    case 89:
                        break;
                    case 21: {
                        return TERM_QUESTION;
                    }
                    // fall through
                    case 90:
                        break;
                    case 22: {
                        return TERM_AT;
                    }
                    // fall through
                    case 91:
                        break;
                    case 23: {
                        return IDENTIFIER;
                    }
                    // fall through
                    case 92:
                        break;
                    case 24: {
                        return TERM_BRACKET_SQUARE_L;
                    }
                    // fall through
                    case 93:
                        break;
                    case 25: {
                        return TERM_BRACKET_SQUARE_R;
                    }
                    // fall through
                    case 94:
                        break;
                    case 26: {
                        return OP_BIT_XOR;
                    }
                    // fall through
                    case 95:
                        break;
                    case 27: {
                        return TERM_CURLY_L;
                    }
                    // fall through
                    case 96:
                        break;
                    case 28: {
                        return OP_BIT_OR;
                    }
                    // fall through
                    case 97:
                        break;
                    case 29: {
                        return TERM_CURLY_R;
                    }
                    // fall through
                    case 98:
                        break;
                    case 30: {
                        return OP_BIT_REVERSE;
                    }
                    // fall through
                    case 99:
                        break;
                    case 31: {
                        return OP_NE;
                    }
                    // fall through
                    case 100:
                        break;
                    case 32: {
                        return TERM_CONST_STRING;
                    }
                    // fall through
                    case 101:
                        break;
                    case 33: {
                        return OP_AND;
                    }
                    // fall through
                    case 102:
                        break;
                    case 34: {
                        return TERM_CONST_STRING_SINGLE;
                    }
                    // fall through
                    case 103:
                        break;
                    case 35: {
                        return WORD;
                    }
                    // fall through
                    case 104:
                        break;
                    case 36: {
                        return OP_BIT_LMOV;
                    }
                    // fall through
                    case 105:
                        break;
                    case 37: {
                        return OP_LTE;
                    }
                    // fall through
                    case 106:
                        break;
                    case 38: {
                        return OP_EQ;
                    }
                    // fall through
                    case 107:
                        break;
                    case 39: {
                        return OP_GTE;
                    }
                    // fall through
                    case 108:
                        break;
                    case 40: {
                        return OP_BIT_RMOV;
                    }
                    // fall through
                    case 109:
                        break;
                    case 41: {
                        return KW_EQ;
                    }
                    // fall through
                    case 110:
                        break;
                    case 42: {
                        return KW_GT;
                    }
                    // fall through
                    case 111:
                        break;
                    case 43: {
                        return KW_IN;
                    }
                    // fall through
                    case 112:
                        break;
                    case 44: {
                        return KW_LT;
                    }
                    // fall through
                    case 113:
                        break;
                    case 45: {
                        return KW_NE;
                    }
                    // fall through
                    case 114:
                        break;
                    case 46: {
                        return KW_OR;
                    }
                    // fall through
                    case 115:
                        break;
                    case 47: {
                        return OP_OR;
                    }
                    // fall through
                    case 116:
                        break;
                    case 48: {
                        return TERM_CONST_NUMBER_FLOAT;
                    }
                    // fall through
                    case 117:
                        break;
                    case 49: {
                        return TERM_CONST_NUMBER_BIN;
                    }
                    // fall through
                    case 118:
                        break;
                    case 50: {
                        return TERM_CONST_NUMBER_SCIEN_1;
                    }
                    // fall through
                    case 119:
                        break;
                    case 51: {
                        return TERM_CONST_NUMBER_OTC;
                    }
                    // fall through
                    case 120:
                        break;
                    case 52: {
                        return TERM_CONST_NUMBER_HEX;
                    }
                    // fall through
                    case 121:
                        break;
                    case 53: {
                        return OP_BIT_RSMOV;
                    }
                    // fall through
                    case 122:
                        break;
                    case 54: {
                        return KW_AND;
                    }
                    // fall through
                    case 123:
                        break;
                    case 55: {
                        return KW_BOR;
                    }
                    // fall through
                    case 124:
                        break;
                    case 56: {
                        return KW_GTE;
                    }
                    // fall through
                    case 125:
                        break;
                    case 57: {
                        return KW_LTE;
                    }
                    // fall through
                    case 126:
                        break;
                    case 58: {
                        return KW_NEQ;
                    }
                    // fall through
                    case 127:
                        break;
                    case 59: {
                        return KW_NEW;
                    }
                    // fall through
                    case 128:
                        break;
                    case 60: {
                        return KW_NOT;
                    }
                    // fall through
                    case 129:
                        break;
                    case 61: {
                        return KW_SHL;
                    }
                    // fall through
                    case 130:
                        break;
                    case 62: {
                        return KW_SHR;
                    }
                    // fall through
                    case 131:
                        break;
                    case 63: {
                        return KW_XOR;
                    }
                    // fall through
                    case 132:
                        break;
                    case 64: {
                        return KW_BAND;
                    }
                    // fall through
                    case 133:
                        break;
                    case 65: {
                        return KW_CONST_NULL;
                    }
                    // fall through
                    case 134:
                        break;
                    case 66: {
                        return KW_CONST_BOOLEAN;
                    }
                    // fall through
                    case 135:
                        break;
                    case 67: {
                        return KW_USHR;
                    }
                    // fall through
                    case 136:
                        break;
                    case 68: {
                        return TERM_CONST_NUMBER_SCIEN_2;
                    }
                    // fall through
                    case 137:
                        break;
                    case 69: {
                        return KW_INSTANCEOF;
                    }
                    // fall through
                    case 138:
                        break;
                    default:
                        zzScanError(ZZ_NO_MATCH);
                }
            }
        }
    }


}
