# spring 配置
spring:
  # 激活配置
  profiles:
    active: dev
  # 应用配置
  application:
    name: maven-project
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 300MB
      # 设置总上传的文件大小
      max-request-size: 2048MB
  # 热部署
  devtools:
    restart:
      # 热部署开关
      enabled: true
      # 排除监听改变的路径
      exclude: logs/**,metas/**

# 环境配置
server:
  # tomcat 配置
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30

# 日志配置
logging:
  level:
    root: info
