spring:
  application:
    name: spring-ai-chat
  ai:
    model:
      chat: openai
    ollama:
      chat:
        enabled: true
      base-url: http://localhost:11434
      options:
        model: deepseek-r1:1.5b
        format: json
        keep_alive: 5m
        temperature: 0.7
      init:
        pull-model-strategy: never
        timeout: 5m
        max-retries: 0
        chat:
          include: true
    openai:
      base-url: https://dashscope.aliyuncs.com/compatible-mode/
      api-key: xxx
      chat:
        options:
          model: deepseek-r1
          temperature: 0.7

i2f:
  ai:
    chat:
      default-system: 你是一个资深植物学家，熟悉每种植物的养殖以及习性，根据用户问题，回答问题
      allow-auto-create-session-id: true
      allow-cookie-session-id: true

logging:
  level:
    org.springframework.ai: trace