spring:
  application:
    name: spring-ai-chat
  ai:
    model:
      chat: openai
    ollama:
      chat:
        enabled: true
      base-url: http://localhost:11434
      options:
        model: deepseek-r1:1.5b
        format: json
        keep_alive: 5m
        temperature: 0.7
      init:
        pull-model-strategy: never
        timeout: 5m
        max-retries: 0
        chat:
          include: true
    openai:
      base-url: https://dashscope.aliyuncs.com/compatible-mode/
      api-key: xxx
      chat:
        options:
          model: qwen-plus
          temperature: 0.7

i2f:
  ai:
    chat:
      enable: true
      chat-client:
        enable: true
      chat-memory:
        enable: true
        impl:
          in-memory: true
      session-repository: enable
      auth-provider: enable
      default-system: 你是一个资深植物学家，熟悉每种植物的养殖以及习性，根据用户问题，回答问题
      default-system-resource: ''
      api:
        chat:
          enable: true
        history:
          enable: true
        session:
          enable: true
      cors:
        enable: true
      web-ui:
        enable: true
        allow-redirect-root-url: false
      allow-auto-create-session-id: true
      allow-cookie-session-id: true
      support-tools: true
      tool-classes:
        - i2f.spring.ai.chat.tools.FileSystemTools
        - i2f.spring.ai.chat.tools.DatabaseMetadataTools
      tool-names:
        - baiduSearchTools

logging:
  level:
    org.springframework.ai: trace