const SwlWebConsts = {
    ACCESS_CONTROL_EXPOSE_HEADERS: () => "Access-Control-Expose-Headers",

    SWL_REQUEST_RAW_HEADER_ATTR_KEY: () => "SWL_RAW_HEADER",
    SWL_REQUEST_HEADER_ATTR_KEY: () => "SWL_HEADER",
    SWL_REQUEST_DECRYPT_ATTR_KEY: () => "SWL_DECRYPTED",
    SWL_REQUEST_DECRYPT_EXCEPTION_ATTR_KEY: () => "SWL_EXCEPTION",
    SWL_RESPONSE_ENCRYPT_ATTR_KEY: () => "SWL_ENCRYPTED",

    SWL_REQUIRE_ENCRYPT_RESPONSE: () => "SWL_REQUIRE_ENCRYPT_RESPONSE",
    SWL_STRING_RESPONSE: () => "SWL_STRING_RESPONSE",
}

export default SwlWebConsts