-- table ddl

-- -------------------------------------------------
-- 1.1 :   XXL_JOB_GROUP

-- DROP TABLE XXL_JOB_GROUP;

CREATE TABLE XXL_JOB_GROUP
(
    ID           BIGINT ( 64 ) NOT NULL,
    APP_NAME     VARCHAR(64) NOT NULL,
    TITLE        VARCHAR(64) NOT NULL,
    ADDRESS_TYPE INTEGER ( 32 ) DEFAULT 0 NOT NULL,
    ADDRESS_LIST VARCHAR(1000000000),
    UPDATE_TIME  TIMESTAMP(26, 6
)
    , PRIMARY KEY ( ID )  );


CREATE UNIQUE INDEX PRIMARY_KEY_B
    ON XXL_JOB_GROUP (ID);



COMMENT
ON TABLE XXL_JOB_GROUP IS '任务组'

        COMMENT ON COLUMN XXL_JOB_GROUP.ID IS 'ID' ;
            COMMENT
ON COLUMN XXL_JOB_GROUP.APP_NAME IS '执行器appname' ;
            COMMENT
ON COLUMN XXL_JOB_GROUP.TITLE IS '执行器名称' ;
            COMMENT
ON COLUMN XXL_JOB_GROUP.ADDRESS_TYPE IS '执行器地址类型：0=自动注册、1=手动录入' ;
            COMMENT
ON COLUMN XXL_JOB_GROUP.ADDRESS_LIST IS '执行器地址列表，多地址逗号分隔' ;
            COMMENT
ON COLUMN XXL_JOB_GROUP.UPDATE_TIME IS '更新时间' ;
    

-- -------------------------------------------------
-- 1.2 :   XXL_JOB_INFO

-- DROP TABLE XXL_JOB_INFO;

CREATE TABLE XXL_JOB_INFO
(
    ID        BIGINT ( 64 ) NOT NULL,
    JOB_GROUP INTEGER ( 32 ) NOT NULL,
    JOB_DESC  VARCHAR(255) NOT NULL,
    ADD_TIME  TIMESTAMP(26, 6
) ,
         UPDATE_TIME TIMESTAMP ( 26 ,6 ) , 
         AUTHOR VARCHAR ( 64 ) , 
         ALARM_EMAIL VARCHAR ( 255 ) , 
         SCHEDULE_TYPE VARCHAR ( 50 ) DEFAULT 'NONE' NOT NULL , 
         SCHEDULE_CONF VARCHAR ( 128 ) , 
         MISFIRE_STRATEGY VARCHAR ( 50 ) DEFAULT 'DO_NOTHING' NOT NULL , 
         EXECUTOR_ROUTE_STRATEGY VARCHAR ( 50 ) , 
         EXECUTOR_HANDLER VARCHAR ( 255 ) , 
         EXECUTOR_PARAM VARCHAR ( 512 ) , 
         EXECUTOR_BLOCK_STRATEGY VARCHAR ( 50 ) , 
         EXECUTOR_TIMEOUT INTEGER ( 32 ) DEFAULT 0 NOT NULL , 
         EXECUTOR_FAIL_RETRY_COUNT INTEGER ( 32 ) DEFAULT 0 NOT NULL , 
         GLUE_TYPE VARCHAR ( 50 ) NOT NULL , 
         GLUE_SOURCE VARCHAR ( 1000000000 ) , 
         GLUE_REMARK VARCHAR ( 128 ) , 
         GLUE_UPDATETIME TIMESTAMP ( 26 ,6 ) , 
         CHILD_JOBID VARCHAR ( 255 ) , 
         TRIGGER_STATUS INTEGER ( 32 ) DEFAULT 0 NOT NULL , 
         TRIGGER_LAST_TIME BIGINT ( 64 ) DEFAULT 0 NOT NULL , 
         TRIGGER_NEXT_TIME BIGINT ( 64 ) DEFAULT 0 NOT NULL 



     , PRIMARY KEY ( ID )  );


CREATE UNIQUE INDEX PRIMARY_KEY_2
    ON XXL_JOB_INFO (ID);



COMMENT
ON TABLE XXL_JOB_INFO IS 'XXL任务信息'

        COMMENT ON COLUMN XXL_JOB_INFO.ID IS 'ID' ;
            COMMENT
ON COLUMN XXL_JOB_INFO.JOB_GROUP IS '执行器主键id' ;
            COMMENT
ON COLUMN XXL_JOB_INFO.JOB_DESC IS '任务降序' ;
            COMMENT
ON COLUMN XXL_JOB_INFO.ADD_TIME IS '加时间' ;
            COMMENT
ON COLUMN XXL_JOB_INFO.UPDATE_TIME IS '更新时间' ;
            COMMENT
ON COLUMN XXL_JOB_INFO.AUTHOR IS '作者' ;
            COMMENT
ON COLUMN XXL_JOB_INFO.ALARM_EMAIL IS '报警邮件' ;
            COMMENT
ON COLUMN XXL_JOB_INFO.SCHEDULE_TYPE IS '调度类型' ;
            COMMENT
ON COLUMN XXL_JOB_INFO.SCHEDULE_CONF IS '调度配置，值含义取决于调度类型' ;
            COMMENT
ON COLUMN XXL_JOB_INFO.MISFIRE_STRATEGY IS '调度过期策略' ;
            COMMENT
ON COLUMN XXL_JOB_INFO.EXECUTOR_ROUTE_STRATEGY IS '执行器路由策略' ;
            COMMENT
ON COLUMN XXL_JOB_INFO.EXECUTOR_HANDLER IS '执行器任务handler' ;
            COMMENT
ON COLUMN XXL_JOB_INFO.EXECUTOR_PARAM IS '执行器任务参数' ;
            COMMENT
ON COLUMN XXL_JOB_INFO.EXECUTOR_BLOCK_STRATEGY IS '阻塞处理策略' ;
            COMMENT
ON COLUMN XXL_JOB_INFO.EXECUTOR_TIMEOUT IS '任务执行超时时间，单位秒' ;
            COMMENT
ON COLUMN XXL_JOB_INFO.EXECUTOR_FAIL_RETRY_COUNT IS '失败重试次数' ;
            COMMENT
ON COLUMN XXL_JOB_INFO.GLUE_TYPE IS 'glue类型' ;
            COMMENT
ON COLUMN XXL_JOB_INFO.GLUE_SOURCE IS 'glue源代码' ;
            COMMENT
ON COLUMN XXL_JOB_INFO.GLUE_REMARK IS '胶水备注' ;
            COMMENT
ON COLUMN XXL_JOB_INFO.GLUE_UPDATETIME IS 'glue更新时间' ;
            COMMENT
ON COLUMN XXL_JOB_INFO.CHILD_JOBID IS '子任务id，多个逗号分隔' ;
            COMMENT
ON COLUMN XXL_JOB_INFO.TRIGGER_STATUS IS '调度状态：0-停止，1-运行' ;
            COMMENT
ON COLUMN XXL_JOB_INFO.TRIGGER_LAST_TIME IS '上次调度时间' ;
            COMMENT
ON COLUMN XXL_JOB_INFO.TRIGGER_NEXT_TIME IS '下次调度时间' ;
    

-- -------------------------------------------------
-- 1.3 :   XXL_JOB_LOCK

-- DROP TABLE XXL_JOB_LOCK;

CREATE TABLE XXL_JOB_LOCK
(
    LOCK_NAME VARCHAR(50) NOT NULL,
    PRIMARY KEY (LOCK_NAME)
);


CREATE UNIQUE INDEX PRIMARY_KEY_2F02
    ON XXL_JOB_LOCK (LOCK_NAME);



COMMENT
ON TABLE XXL_JOB_LOCK IS 'XXL任务锁'

        COMMENT ON COLUMN XXL_JOB_LOCK.LOCK_NAME IS '锁名称' ;
    

-- -------------------------------------------------
-- 1.4 :   XXL_JOB_LOG

-- DROP TABLE XXL_JOB_LOG;

CREATE TABLE XXL_JOB_LOG
(
    ID                        BIGINT ( 64 ) NOT NULL,
    JOB_GROUP                 INTEGER ( 32 ) NOT NULL,
    JOB_ID                    INTEGER ( 32 ) NOT NULL,
    EXECUTOR_ADDRESS          VARCHAR(255),
    EXECUTOR_HANDLER          VARCHAR(255),
    EXECUTOR_PARAM            VARCHAR(512),
    EXECUTOR_SHARDING_PARAM   VARCHAR(20),
    EXECUTOR_FAIL_RETRY_COUNT INTEGER ( 32 ) DEFAULT 0 NOT NULL,
    TRIGGER_TIME              TIMESTAMP(26, 6
) ,
         TRIGGER_CODE INTEGER ( 32 ) NOT NULL , 
         TRIGGER_MSG VARCHAR ( 1000000000 ) , 
         HANDLE_TIME TIMESTAMP ( 26 ,6 ) , 
         HANDLE_CODE INTEGER ( 32 ) NOT NULL , 
         HANDLE_MSG VARCHAR ( 1000000000 ) , 
         ALARM_STATUS INTEGER ( 32 ) DEFAULT 0 NOT NULL 



     , PRIMARY KEY ( ID )  );


CREATE UNIQUE INDEX PRIMARY_KEY_8
    ON XXL_JOB_LOG (ID);



CREATE INDEX IDX_XXL_JOB_LOG_HANDLE_CODE
    ON XXL_JOB_LOG (HANDLE_CODE);
CREATE INDEX IDX_XXL_JOB_LOG_TRIGGER_TIME
    ON XXL_JOB_LOG (TRIGGER_TIME);

COMMENT
ON TABLE XXL_JOB_LOG IS 'XXL任务日志'

        COMMENT ON COLUMN XXL_JOB_LOG.ID IS 'ID' ;
            COMMENT
ON COLUMN XXL_JOB_LOG.JOB_GROUP IS '执行器主键id' ;
            COMMENT
ON COLUMN XXL_JOB_LOG.JOB_ID IS '任务，主键id' ;
            COMMENT
ON COLUMN XXL_JOB_LOG.EXECUTOR_ADDRESS IS '执行器地址，本次执行的地址' ;
            COMMENT
ON COLUMN XXL_JOB_LOG.EXECUTOR_HANDLER IS '执行器任务handler' ;
            COMMENT
ON COLUMN XXL_JOB_LOG.EXECUTOR_PARAM IS '执行器任务参数' ;
            COMMENT
ON COLUMN XXL_JOB_LOG.EXECUTOR_SHARDING_PARAM IS '执行器任务分片参数，格式如 1/2' ;
            COMMENT
ON COLUMN XXL_JOB_LOG.EXECUTOR_FAIL_RETRY_COUNT IS '失败重试次数' ;
            COMMENT
ON COLUMN XXL_JOB_LOG.TRIGGER_TIME IS '调度-时间' ;
            COMMENT
ON COLUMN XXL_JOB_LOG.TRIGGER_CODE IS '调度-结果' ;
            COMMENT
ON COLUMN XXL_JOB_LOG.TRIGGER_MSG IS '调度-日志' ;
            COMMENT
ON COLUMN XXL_JOB_LOG.HANDLE_TIME IS '执行-时间' ;
            COMMENT
ON COLUMN XXL_JOB_LOG.HANDLE_CODE IS '执行-状态' ;
            COMMENT
ON COLUMN XXL_JOB_LOG.HANDLE_MSG IS '执行-日志' ;
            COMMENT
ON COLUMN XXL_JOB_LOG.ALARM_STATUS IS '告警状态：0-默认、1-无需告警、2-告警成功、3-告警失败' ;
    

-- -------------------------------------------------
-- 1.5 :   XXL_JOB_LOG_REPORT

-- DROP TABLE XXL_JOB_LOG_REPORT;

CREATE TABLE XXL_JOB_LOG_REPORT
(
    ID          BIGINT ( 64 ) NOT NULL,
    TRIGGER_DAY TIMESTAMP(26, 6
) ,
         RUNNING_COUNT INTEGER ( 32 ) DEFAULT 0 NOT NULL , 
         SUC_COUNT INTEGER ( 32 ) DEFAULT 0 NOT NULL , 
         FAIL_COUNT INTEGER ( 32 ) DEFAULT 0 NOT NULL , 
         UPDATE_TIME TIMESTAMP ( 26 ,6 ) 



     , PRIMARY KEY ( ID )  );


CREATE UNIQUE INDEX PRIMARY_KEY_5
    ON XXL_JOB_LOG_REPORT (ID);



CREATE INDEX IDX_XXL_JOB_LOG_REPORT_TRIGGER_DAY
    ON XXL_JOB_LOG_REPORT (TRIGGER_DAY);

COMMENT
ON TABLE XXL_JOB_LOG_REPORT IS 'XXL任务日志报表'

        COMMENT ON COLUMN XXL_JOB_LOG_REPORT.ID IS 'ID' ;
            COMMENT
ON COLUMN XXL_JOB_LOG_REPORT.TRIGGER_DAY IS '调度-时间' ;
            COMMENT
ON COLUMN XXL_JOB_LOG_REPORT.RUNNING_COUNT IS '运行中-日志数量' ;
            COMMENT
ON COLUMN XXL_JOB_LOG_REPORT.SUC_COUNT IS '执行成功-日志数量' ;
            COMMENT
ON COLUMN XXL_JOB_LOG_REPORT.FAIL_COUNT IS '执行失败-日志数量' ;
            COMMENT
ON COLUMN XXL_JOB_LOG_REPORT.UPDATE_TIME IS '更新时间' ;
    

-- -------------------------------------------------
-- 1.6 :   XXL_JOB_LOGGLUE

-- DROP TABLE XXL_JOB_LOGGLUE;

CREATE TABLE XXL_JOB_LOGGLUE
(
    ID          BIGINT ( 64 ) NOT NULL,
    JOB_ID      INTEGER ( 32 ) NOT NULL,
    GLUE_TYPE   VARCHAR(50),
    GLUE_SOURCE VARCHAR(1000000000),
    GLUE_REMARK VARCHAR(128) NOT NULL,
    ADD_TIME    TIMESTAMP(26, 6
) ,
         UPDATE_TIME TIMESTAMP ( 26 ,6 ) 



     , PRIMARY KEY ( ID )  );


CREATE UNIQUE INDEX PRIMARY_KEY_A
    ON XXL_JOB_LOGGLUE (ID);



COMMENT
ON TABLE XXL_JOB_LOGGLUE IS 'XXL任务logglue'

        COMMENT ON COLUMN XXL_JOB_LOGGLUE.ID IS 'ID' ;
            COMMENT
ON COLUMN XXL_JOB_LOGGLUE.JOB_ID IS '任务，主键id' ;
            COMMENT
ON COLUMN XXL_JOB_LOGGLUE.GLUE_TYPE IS 'glue类型' ;
            COMMENT
ON COLUMN XXL_JOB_LOGGLUE.GLUE_SOURCE IS 'glue源代码' ;
            COMMENT
ON COLUMN XXL_JOB_LOGGLUE.GLUE_REMARK IS 'glue备注' ;
            COMMENT
ON COLUMN XXL_JOB_LOGGLUE.ADD_TIME IS '加时间' ;
            COMMENT
ON COLUMN XXL_JOB_LOGGLUE.UPDATE_TIME IS '更新时间' ;
    

-- -------------------------------------------------
-- 1.7 :   XXL_JOB_REGISTRY

-- DROP TABLE XXL_JOB_REGISTRY;

CREATE TABLE XXL_JOB_REGISTRY
(
    ID             BIGINT ( 64 ) NOT NULL,
    REGISTRY_GROUP VARCHAR(50)  NOT NULL,
    REGISTRY_KEY   VARCHAR(255) NOT NULL,
    REGISTRY_VALUE VARCHAR(255) NOT NULL,
    UPDATE_TIME    TIMESTAMP(26, 6
)
    , PRIMARY KEY ( ID )  );


CREATE UNIQUE INDEX PRIMARY_KEY_2F
    ON XXL_JOB_REGISTRY (ID);



CREATE INDEX IDX_XXL_JOB_REGISTRY_G_K_V
    ON XXL_JOB_REGISTRY (REGISTRY_GROUP, REGISTRY_KEY, REGISTRY_VALUE);

COMMENT
ON TABLE XXL_JOB_REGISTRY IS 'XXL任务注册'

        COMMENT ON COLUMN XXL_JOB_REGISTRY.ID IS 'ID' ;
            COMMENT
ON COLUMN XXL_JOB_REGISTRY.REGISTRY_GROUP IS '注册组' ;
            COMMENT
ON COLUMN XXL_JOB_REGISTRY.REGISTRY_KEY IS '注册键' ;
            COMMENT
ON COLUMN XXL_JOB_REGISTRY.REGISTRY_VALUE IS '注册值' ;
            COMMENT
ON COLUMN XXL_JOB_REGISTRY.UPDATE_TIME IS '更新时间' ;
    

-- -------------------------------------------------
-- 1.8 :   XXL_JOB_USER

-- DROP TABLE XXL_JOB_USER;

CREATE TABLE XXL_JOB_USER
(
    ID         BIGINT ( 64 ) NOT NULL,
    USERNAME   VARCHAR(50)  NOT NULL,
    PASSWORD   VARCHAR(300) NOT NULL,
    ROLE       INTEGER ( 32 ) NOT NULL,
    PERMISSION VARCHAR(255),
    PRIMARY KEY (ID)
);


CREATE UNIQUE INDEX IDX_XXL_JOB_USER_USERNAME
    ON XXL_JOB_USER (USERNAME);

CREATE UNIQUE INDEX PRIMARY_KEY_2F0
    ON XXL_JOB_USER (ID);



COMMENT
ON TABLE XXL_JOB_USER IS 'XXL任务用户'

        COMMENT ON COLUMN XXL_JOB_USER.ID IS 'ID' ;
            COMMENT
ON COLUMN XXL_JOB_USER.USERNAME IS '账号' ;
            COMMENT
ON COLUMN XXL_JOB_USER.PASSWORD IS '密码' ;
            COMMENT
ON COLUMN XXL_JOB_USER.ROLE IS '角色：0-普通用户、1-管理员' ;
            COMMENT
ON COLUMN XXL_JOB_USER.PERMISSION IS '权限：执行器id列表，多个逗号分割' ;
    

